modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Quick%20Paths"
logoFile="icon.png"

[[mods]]
modId="quickpaths"
version="3.2"
displayName="Quick Paths"
displayURL="https://serilum.com/mod/quick-paths"
authors="Rick South"
description='''Create long paths instantly by setting a start and end point.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.quickpaths]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.quickpaths]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "quickpaths_neoforge.mixins.json"